#generic
zehero: "ZE HERO"
zehero_logo_white: https://res.cloudinary.com/deddrj0yb/image/upload/v1641893182/website/logo/Sur%20fond%20colore%CC%81/logo-ze-hero-sans-slogan_8_xs7f9w.png
zehero_logo_brown: https://res.cloudinary.com/deddrj0yb/image/upload/v1640094644/website/logo/Sur%20fond%20clair/logo-ze-hero-sans-slogan_7_navyp9.png
zehero_logo_black: https://res.cloudinary.com/deddrj0yb/image/upload/v1640094645/website/logo/Sur%20fond%20fonce%CC%81/logo-ze-hero-sans-slogan_9_nj7apy.png

#open graph
og_url: https://preprod-zehero-202112.netlify.app

#social networks
facebook:
  title: Facebook
  facebook_username: https://www.facebook.com/Zehero73/
linkedin:
  title: Linkedin
  linkedin_username:  https://www.linkedin.com/company/ze-hero-outdoor/
instagram:
  title: Instagram
  instagram_username: https://www.instagram.com/zehero_officiel/

#languages
languages: [fr,en]

#list season
seasons: [winter,summer]

fr:
  changelang: Parcourir le site en français
  footer_baseline: Découvrez les activités près de chez vous et profitez d’expériences inoubliables seul, entre amis ou en famille !
  season:
    winter: 
      name: hiver
      icon: icon-feather-cloud-snow
      icon-link-title: Lien vers la saison d'hiver
    summer: 
      name: ete
      icon: icon-feather-sun
      icon-link-title: Lien vers la saison d'été
  newsletter:
    privacy: Nous nous engageons à protéger votre vie privée. Nous ne collecterons jamais d'informations vous concernant sans votre consentement explicite.
    title: Recevez nos dernières informations outdoor
    placeholder: Entrez votre adresse email
    subscribe-btn: Je m'inscris
  blog:
    various:
      text001: De
      text002: le
      text003: Lire tous mes articles
    related-posts:
      caption: Vous aimerez aussi
      title: Dans le même univers
  activity:
    readmore: Explorer cette activité
  resort:
    readmore: Visiter cette destination
  contact:
    icon-link-title: Lien vers notre page de contact
  section-blog: 
    winter:
      image_href: https://res.cloudinary.com/deddrj0yb/image/upload/v1640080084/website/winter/pablo-guerrero-xglh7hBu9QU-unsplash_nvbvyf.jpg
    summer:
      image_href: https://res.cloudinary.com/deddrj0yb/image/upload/v1638883619/website/summer/Sommet-montagne-randonnee_nhpjve.jpg
    txt01: Envie d'être informé
    txt01b: des offres
    txt01c: et des conseils
    txt02: La newsletter ZE HERO est pour vous.
    txt03: Inscrivez-vous pour des infos exclusives
    txt04: m'inscrire
    txt05: En direct du blog
    txt06: Les derniers articles
    txt07: Lien vers l'aticle de blog

en:
  changelang: Navigate this website in english
  footer_baseline: Découvrez les activités près de chez vous et profitez d’expériences inoubliables seul, entre amis ou en famille !
  season:
    winter: 
      name: winter
      icon: icon-feather-cloud-snow
      icon-link-title: Go to the winter season
    summer: 
      name: summer
      icon: icon-feather-sun
      icon-link-title: Go to the summer season
  newsletter:
    privacy: We are committed to protecting your privacy. We will never collect information about you without your explicit consent.
    title: Get our latest outdoor updates
    placeholder: Enter your email address
    subscribe-btn: Subscribe
  blog:
    related-posts:
      caption: You may also like
      title: Related posts
  activity:
    readmore: Explore more
  resort:
    readmore: Visit this destination
  contact:
    icon-link-title: Go to our contact page
  section-blog: 
    winter:
      image_href: https://res.cloudinary.com/deddrj0yb/image/upload/v1640080084/website/winter/pablo-guerrero-xglh7hBu9QU-unsplash_nvbvyf.jpg
    summer:
      image_href: https://res.cloudinary.com/deddrj0yb/image/upload/v1638883619/website/summer/Sommet-montagne-randonnee_nhpjve.jpg
    txt01: Want to know everything about
    txt01b: our offers
    txt01c: and advices
    txt02: Want to stay in the loop ?
    txt03: Subscribe to get exclusive news
    txt04: subscribe
    txt05: Live from the blog
    txt06: Our latest blog posts
    txt07: Link to blog post 

#Image resizing by cloudinary
#Cloudinary
cloudinary_url: "https://res.cloudinary.com/deddrj0yb/image/upload"

# {{ imgsize.url }}{{ imgsize.[variable] }}{{[variable].image01_href | remove: 'https://res.cloudinary.com/deddrj0yb/image/upload' }}

# {% include image.html file="" sizevar="" width="" height="" %}

# {% capture download_note %}{{ activity.image01_href }}{% endcapture %}
# <img src="{% include image.html file=download_note sizevar="activitylist" width="" height="" %}" alt="">

img:
  url: https://res.cloudinary.com/deddrj0yb/image/upload/

## List of sizevar variables
#logo
  logo_header: c_fill,w_222,h_57
  logo_headerx2: c_fill,w_444,h_114
  logo_footer: c_fill,w_135,h_36
#activity image in list
  activitylist: c_fill,w_322,h_446
#blog post thumbnail list
  blogpostlist: c_fill,w_600,h_450
#blog post thumbnail list in blog homepage
  homeblogpostlist: c_fill,w_800,h_970
#blog post image hero in the post
  blogposthero: c_fill,w_1300,h_800
#image gallery style 2
  bigsquare: c_fill,w_800,h_803
  rectangle: c_fill,w_800,h_387
  smlsquare: c_fill,w_400,h_400
#resort hero image
  resorthero: c_fill,w_1200,h_700
#generic
  genhero: c_fill,w_1500,h_1200