#generic
zehero: "ZE HERO"

#Cloudinary
cloudinary_url: "https://res.cloudinary.com/deddrj0yb/image/upload"

#languages
languages: [fr,en]

#list season
seasons: [winter,summer]

fr:
  season:
    winter: 
      name: hiver
      icon: icon-feather-cloud-snow
    summer: 
      name: ete
      icon: icon-feather-sun
en:
  season:
    winter: 
      name: winter
      icon: icon-feather-cloud-snow
    summer: 
      name: summer
      icon: icon-feather-sun

#common text
slogan:
  fr:
    owol: "Outdoor Way Of Life"
  en: 
    owol: "Outdoor Way Of Life"