#languages
languages: [fr,en]

#list season
seasons: [winter,summer]

fr:
  season:
    winter: 
      name: hiver
      icon: icon-feather-cloud-snow
      color: text-black
    summer: 
      name: ete
      icon: icon-feather-sun
      color: text-black
en:
  season:
    winter: 
      name: winter
      icon: icon-feather-cloud-snow
      color: text-black
    summer: 
      name: summer
      icon: icon-feather-sun
      color: text-black

#common text
slogan:
  fr:
    owol: "Outdoor Way Of Life"
  en: 
    owol: "Outdoor Way Of Life"