#generic
site: "ZE HERO"
site_logo_white: https://res.cloudinary.com/deddrj0yb/image/upload/v1641893182/website/logo/Sur%20fond%20colore%CC%81/logo-ze-hero-sans-slogan_8_xs7f9w.png
site_logo_brown: https://res.cloudinary.com/deddrj0yb/image/upload/v1640094644/website/logo/Sur%20fond%20clair/logo-ze-hero-sans-slogan_7_navyp9.png
site_logo_black: https://res.cloudinary.com/deddrj0yb/image/upload/v1640094645/website/logo/Sur%20fond%20fonce%CC%81/logo-ze-hero-sans-slogan_9_nj7apy.png

phonenumber: (+33) 4 79 22 35 27

site-color: green
site-color2: radical-red

#open graph
og_url: https://www.ze-hero.com

  #social networks (3 max)
socials:
  - title: Facebook
    facebook_username: https://www.facebook.com/Zehero73/
    icon: fab fa-facebook-square
  - title: Linkedin
    linkedin_username:  https://www.linkedin.com/company/ze-hero-outdoor/
    icon: fab fa-linkedin
  - title: Instagram
    instagram_username: https://www.instagram.com/zehero_officiel/
    icon: fab fa-instagram

#languages
multilangue: false
languages: [fr]
menu_lang:
  - item: fr
    title: Français
    altext: Lien vers la version française du site
    link: /fr/
    flag_url: https://res.cloudinary.com/fausse-route/image/upload/v1646159690/website/logos/pays/france.png
  - item: en
    title: English
    altext: Go to english version
    link: /en/
    flag_url: https://res.cloudinary.com/fausse-route/image/upload/v1646159685/website/logos/pays/United_Kingdom_Great_Britain.png

#list season
seasons: [winter,summer]

fr:
  changelang: Parcourir le site en français
  footer_baseline: Être le héro de son temps libre. Ressentir cette fierté intense, le sentiment de partage, la satisfaction personnelle, le plaisir et le dépassement lors de vos activités Outdoor
  season:
    winter: 
      name: hiver
      icon: feather icon-feather-toggle-right icon-extra-medium
      icon-link-title: Lien vers la saison d'hiver
    summer: 
      name: ete
      icon: feather icon-feather-toggle-left icon-extra-medium
      icon-link-title: Lien vers la saison d'été
  newsletter:
    privacy: Nous nous engageons à protéger votre vie privée. Nous ne collecterons jamais d'informations vous concernant sans votre consentement explicite.
    title: Recevez nos dernières informations outdoor
    placeholder: Entrez votre adresse email
    subscribe-btn: Je m'inscris
  blog:
    various:
      text001: De
      text002: le
      text003: Lire tous mes articles
    component:
      baseline: En direct du blog
      title: Nos dernières actualités
    related-posts:
      caption: Vous aimerez aussi
      title: Dans le même univers
  activity:
    readmore: Explorer cette activité
    winter:
      extendh1: ", votre prochaine activité de l'hiver"
    summer:
      extendh1: ", votre prochaine activité de l'été"
  coach:
    winter:
      extendh1: "Votre coach sportif de l'hiver, "
    summer:
      extendh1: "Votre coach sportif de l'été, " 
  brand:
    extendh1: ", une marque aux valeurs fortes comme ZE HERO "
  advice:
    readmore: Lire ce conseil
  resort:
    readmore: Visiter cette destination
  contact:
    icon-link-title: Lien vers notre page de contact
  section-blog: 
    winter:
      image_href: https://res.cloudinary.com/deddrj0yb/image/upload/v1640080084/website/winter/pablo-guerrero-xglh7hBu9QU-unsplash_nvbvyf.jpg
    summer:
      image_href: https://res.cloudinary.com/deddrj0yb/image/upload/v1638883619/website/summer/Sommet-montagne-randonnee_nhpjve.jpg
    txt01: Envie d'être informé
    txt01b: des offres
    txt01c: et des conseils
    txt02: La newsletter ZE HERO est pour vous.
    txt03: Inscrivez-vous pour des infos exclusives
    txt04: m'inscrire
    txt05: En direct du blog
    txt06: Les derniers articles
    txt07: Lien vers l'aticle de blog
  various:
    readmore: Lire la suite
    link-to: Lien vers la page
  top-menu:
    winter:
      btn_text: e-Shop
      btn_href: https://shop.ze-hero.com/achat-occasion/
      btn_href_title: Lien vers la page du e-shop
    summer:
      btn_text: e-Shop
      btn_href: https://shop.ze-hero.com/achat-occasion/
      btn_href_title: Lien vers la page du e-shop
  modal-eshop-menu:
    winter:
      btn_text: Réserver
      btn_href: https://shop.ze-hero.com/achat-occasion/
      btn_href_title: Lien vers la page du e-shop pour réserver vos activités outdoor de l'hiver
      btn_text02: Contact
      btn_href_title02: Contactez l'équipe de ZE HERO pour toutes vos questions relatives aux activités outdoor, pour un conseil matériel ou des rensignements sur une offre, une destination ou autre
      contact-modal-txt01: Nous répondons à toutes vos questions<br> via ce formulaire ou par téléphone au
    summer:
      btn_text: Réserver
      btn_href: https://shop.ze-hero.com/activites-Outdoor?calessonstype=all&catypegenderlistsummer=all&calessonsactivitytype=Surf&start-date=
      btn_href_title: Lien vers la page du e-shop pour réserver vos activités outdoor de l'été
      btn_text02: Contact
      btn_href_title02: Contactez l'équipe de ZE HERO pour toutes vos questions relatives aux activités outdoor, pour un conseil matériel ou des rensignements sur une offre, une destination ou autre
      contact-modal-txt01: Nous répondons à toutes vos questions<br> via ce formulaire ou par téléphone au
en:
  changelang: Navigate this website in english
  footer_baseline: Be the hero of your free time. Feel the intense pride, the feeling of sharing, the personal satisfaction, the fun and the challenge during your outdoor activities
  season:
    winter: 
      name: winter
      icon: icon-feather-cloud-snow
      icon-link-title: Go to the winter season
    summer: 
      name: summer
      icon: icon-feather-sun
      icon-link-title: Go to the summer season
  newsletter:
    privacy: We are committed to protecting your privacy. We will never collect information about you without your explicit consent.
    title: Get our latest outdoor updates
    placeholder: Enter your email address
    subscribe-btn: Subscribe
  blog:
    component:
      baseline: Live from the blog
      title: Our latest stories & news
    related-posts:
      caption: You may also like
      title: Related posts
  activity:
    readmore: Explore more
    winter:
      extendh1: ", your next winter activity"
    summer:
      extendh1: ", your next summer activity"
  coach:
    winter:
      extendh1: "Your winter training coach, "
    summer:
      extendh1: "Your summer training coach, "
  brand:
    extendh1: ", we partner with this valuable brand"
  advice:
    readmore: Read this advice
  resort:
    readmore: Visit this destination
  contact:
    icon-link-title: Go to our contact page
  section-blog: 
    winter:
      image_href: https://res.cloudinary.com/deddrj0yb/image/upload/v1640080084/website/winter/pablo-guerrero-xglh7hBu9QU-unsplash_nvbvyf.jpg
    summer:
      image_href: https://res.cloudinary.com/deddrj0yb/image/upload/v1638883619/website/summer/Sommet-montagne-randonnee_nhpjve.jpg
    txt01: Want to know everything about
    txt01b: our offers
    txt01c: and advices
    txt02: Want to stay in the loop ?
    txt03: Subscribe to get exclusive news
    txt04: subscribe
    txt05: Live from the blog
    txt06: Our latest blog posts
    txt07: Link to blog post
  various:
    readmore: Read more
    link-to: Link to the page
  top-menu:
    winter:
      btn_text: e-Shop
      btn_href: https://shop.ze-hero.com/achat-occasion/
      btn_href_title: Link to the e-shop page
    summer:
      btn_text: e-Shop
      btn_href: https://shop.ze-hero.com/achat-occasion/
      btn_href_title: Link to the e-shop page
  modal-eshop-menu:
    winter:
      btn_text: e-Shop
      btn_href: https://shop.ze-hero.com/achat-occasion/
      btn_href_title: Link to the e-shop page
      btn_text02: Contact
      btn_href_title02: Contactez l'équipe de ZE HERO pour toutes vos questions relatives aux activités outdoor, pour un conseil matériel ou des rensignements sur une offre, une destination ou autre
    summer:
      btn_text: e-Shop
      btn_href: https://shop.ze-hero.com/activites-Outdoor?calessonstype=all&catypegenderlistsummer=all&calessonsactivitytype=Surf&start-date=
      btn_href_title: Link to the e-shop page
      btn_text02: Contact
      btn_href_title02: Contactez l'équipe de ZE HERO pour toutes vos questions relatives aux activités outdoor, pour un conseil matériel ou des rensignements sur une offre, une destination ou autre

#Image resizing by cloudinary
#Cloudinary
cloudinary_url: "https://res.cloudinary.com/deddrj0yb/image/upload"

# {{ imgsize.url }}{{ imgsize.[variable] }}{{[variable].image01_href | remove: 'https://res.cloudinary.com/deddrj0yb/image/upload' }}


## IMAGE INCLUDE
# {% include image.html file="" sizevar="" width="" height="" %}

# {% capture download_note %}{{ activity.image01_href }}{% endcapture %} 
# <img src="{% include image.html file=download_note sizevar="activitylist" width="" height="" %}" alt="">

## OPTIONS de download_note
#  sizevar="" or width="" and height=""
#  coloreplace="yes"  // "yes" or empty to green colorize the image
#  gradient="grad" // "grad" to add top to bottom black->transparent gradient to image


img:
  url: https://res.cloudinary.com/deddrj0yb/image/upload/

## List of sizevar variables
#logo
  logo_header: c_fill,w_222,h_57/f_auto
  logo_headerx2: c_fill,w_444,h_114/f_auto
  logo_footer: c_fill,w_135,h_36/f_auto
#activity image in list
  activitylist: c_fill,w_322,h_446/f_auto
#blog post thumbnail list
  blogpostlist: c_fill,w_600,h_450/f_auto
#blog post thumbnail list in blog homepage
  homeblogpostlist: c_fill,w_800,h_970/f_auto
#blog post image hero in the post
  blogposthero: c_fill,w_1300,h_800/f_auto
#blog post image content
  blog_width: w_900/f_auto
#image gallery style 2
  bigsquare: c_fill,w_800,h_803/f_auto
  rectangle: c_fill,w_800,h_387/f_auto
  smlsquare: c_fill,w_400,h_400/f_auto
#resort hero image
  resorthero: c_fill,w_1200,h_700/f_auto
#generic
  genhero: c_fill,w_1500,h_1200/f_auto
#eshop thumb product
  thumbstore: c_fill,w_600,h_800/f_auto
  thumbproduct: c_fill,w_600,h_675/f_auto
  bigproduct:  c_fill,w_800,h_1000/f_auto
  descproduct: c_fill,w_800,h_800/f_auto