#generic
zehero: "ZE HERO"

#Cloudinary
cloudinary_url: "https://res.cloudinary.com/deddrj0yb/image/upload"

#languages
languages: [fr,en]

#list season
seasons: [winter,summer]

fr:
  season:
    winter: 
      name: hiver
      icon: icon-feather-cloud-snow
    summer: 
      name: ete
      icon: icon-feather-sun
  newsletter:
    privacy: Nous nous engageons à protéger votre vie privée. Nous ne collecterons jamais d'informations vous concernant sans votre consentement explicite.
    title: Recevez nos dernières informations outdoor
    placeholder: Entrez votre adresse email
    subscribe-btn: Je m'inscris
  blog:
    related-posts:
      caption: Vous aimerez aussi
      title: Dans le même univers

en:
  season:
    winter: 
      name: winter
      icon: icon-feather-cloud-snow
    summer: 
      name: summer
      icon: icon-feather-sun
  newsletter:
    privacy: We are committed to protecting your privacy. We will never collect information about you without your explicit consent.
    title: Get our latest outdoor updates
    placeholder: Enter your email address
    subscribe-btn: Subscribe
  blog:
    related-posts:
      caption: You may also like
      title: Related posts

#common text
slogan:
  fr:
    owol: "Outdoor Way Of Life"
  en: 
    owol: "Outdoor Way Of Life"