#languages
lang_fr: fr
lang_en: en

#list season
seasons: [winter, summer]

fr:
  season:
    winter: 
      name: hiver
      icon: icon-feather-cloud-snow
      color: text-black
    summer: 
      name: ete
      icon: icon-feather-sun
      color: text-black
en:
  season:
    winter: winter
    summer: summer

#common text
slogan:
  fr:
    owol: "Outdoor Way Of Life"
  en: 
    owol: "Outdoor Way Of Life"